version: '3.8'

services:
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  mongodb:
    image: mongo:4.4.4
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/realtime

  spark:
    image: bitnami/spark:3.1.1
    depends_on:
      - kafka
      - mongodb
    command: "spark-submit --class com.example.realtime.SparkProcessor /app/sparkprocessor.jar"
    volumes:
      - ./data-processor/target/sparkprocessor.jar:/app/sparkprocessor.jar
